GET http://localhost:5487/client/ping
X-Server-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf9y
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6eyIkb2lkIjoiNjg2ZGYwZDVhNGUxNjdhNTcwMTRjNTlhIn0sImd1aWQiOiJ0ZXN0dXNlcjEyMyIsImFjY2VzcyI6ImNsaWVudCIsImV4cCI6MTc1MzQxNzk0MSwiaWF0IjoxNzUyMDM1NTQxfQ.Uti0BOFFOyp2jUFDTEfPgpCcPKtazaz1zba7dYH9v-Q
Accept: application/json
