### Get all uploads of a client
GET http://localhost:5487/admin/upload/686d0a550faa2098b958beae
X-Server-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf9y
X-Admin-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf78
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6eyIkb2lkIjoiNjg2ZDFhYjkwMmRhODczY2M1ZTk4NzM2In0sImd1aWQiOiJ0ZXN0YWRtaW4xMjMiLCJhY2Nlc3MiOiJhZG1pbiIsImV4cCI6MTc1MzM2NDI1NCwiaWF0IjoxNzUxOTgxODU0fQ.e3Xd4m5_OjQm74LpYRXqyr417IWVaaCUEWJOB5dQcYw
Accept: application/json

###

### Get a specific upload by client_id and upload_id
GET http://localhost:5487/admin/upload/686d0a550faa2098b958beae/686d20346de60ad8c112e48c
X-Server-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf9y
X-Admin-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf78
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6eyIkb2lkIjoiNjg2ZDFhYjkwMmRhODczY2M1ZTk4NzM2In0sImd1aWQiOiJ0ZXN0YWRtaW4xMjMiLCJhY2Nlc3MiOiJhZG1pbiIsImV4cCI6MTc1MzM2NDI1NCwiaWF0IjoxNzUxOTgxODU0fQ.e3Xd4m5_OjQm74LpYRXqyr417IWVaaCUEWJOB5dQcYw
Accept: application/json

###

### Register a upload to client
POST http://localhost:5487/admin/upload
X-Server-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf9y
X-Admin-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf78
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6eyIkb2lkIjoiNjg2ZDFhYjkwMmRhODczY2M1ZTk4NzM2In0sImd1aWQiOiJ0ZXN0YWRtaW4xMjMiLCJhY2Nlc3MiOiJhZG1pbiIsImV4cCI6MTc1MzM2NDI1NCwiaWF0IjoxNzUxOTgxODU0fQ.e3Xd4m5_OjQm74LpYRXqyr417IWVaaCUEWJOB5dQcYw
Content-Type: application/json
Accept: application/json

{
  "client": "686d4d8799668584c3356f45",
  "src": "/home/harihar/Pictures/192.png"
}

###

### Update a upload
PUT http://localhost:5487/admin/upload
X-Server-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf9y
X-Admin-Key: jprLK8zviZKybwHjCWZ93QMqMmuomyXrpvfbS3US20FMqf78
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6eyIkb2lkIjoiNjg2ZDFhYjkwMmRhODczY2M1ZTk4NzM2In0sImd1aWQiOiJ0ZXN0YWRtaW4xMjMiLCJhY2Nlc3MiOiJhZG1pbiIsImV4cCI6MTc1MzM2NDI1NCwiaWF0IjoxNzUxOTgxODU0fQ.e3Xd4m5_OjQm74LpYRXqyr417IWVaaCUEWJOB5dQcYw
Content-Type: application/json
Accept: application/json

{
  "client_id": "686d0a550faa2098b958beae",
  "upload_id": "686d20346de60ad8c112e48c",
  "status": "completed",
  "result": "{\"output\":\"Task executed successfully\"}"
}

###